name: wordix_site
description: Site web Wordix (landing FR/EN)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.2.2
  flutter_markdown: ^0.7.3
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    # si tu veux des images/screenshots sur le site

    - assets/images/hero_wordix.png

    - assets/screenshots/s1.png
    - assets/screenshots/s2.png
    - assets/screenshots/s3.png

    - assets/legal/privacy.md
    - assets/legal/terms.md
    - assets/legal/legal_notice.md
    - assets/legal/delete_policy.md
